/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:37f6fc12-3806-408f-b87f-7bcd35cd3527",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_UwcfdhZLz",
    "aws_user_pools_web_client_id": "5c8fo0irsp5a9nmcsbt3jsc7o1",
    "oauth": {},
    "aws_content_delivery_bucket": "amplifyconsoleapp-20210405225501-hostingbucket-dev",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "http://amplifyconsoleapp-20210405225501-hostingbucket-dev.s3-website-us-east-1.amazonaws.com"
};


export default awsmobile;
